import Foundation
import Observation
import UserNotifications

/// App state. Tracked claim ids persist across launches; the lifetime
/// entitlement itself is owned by StoreManager (StoreKit is the source
/// of truth), mirrored here for cheap view access.
///
/// @MainActor by contract, not convention: every mutation site is UI-
/// driven or reconciliation, and observers are views. The network hop in
/// `refreshFeed` happens inside FeedStore off this actor.
@Observable @MainActor
final class AppModel {
    private static let trackedKey = "owed.tracked"
    private static let profileKey = "owed.profile"
    private static let profileDoneKey = "owed.profileDone"
    private static let receivedKey = "owed.received"
    private static let calendaredKey = "owed.calendared"
    private static let calendarEventIDsKey = "owed.calendarEventIDs"
    private static let snapshotsKey = "owed.trackedSnapshots"
    private static let deadlineNoticesKey = "owed.deadlineNotices"

    /// Persistence surface. Production uses `.standard`; tests inject an
    /// isolated suite so parallel Swift Testing cases can't leak state.
    private let defaults: UserDefaults

    /// Settlement ids the user has started claims for.
    private(set) var tracked: Set<String> {
        didSet { defaults.set(Array(tracked), forKey: Self.trackedKey) }
    }

    /// The user's yes-answers from the match quiz. On-device only, never
    /// uploaded — local matching is the product's privacy story.
    var profile: Set<MatchKey> {
        didSet { defaults.set(profile.map(\.rawValue), forKey: Self.profileKey) }
    }

    /// Whether the quiz has been offered (completed or skipped) — gates
    /// the first-launch prompt, not the feature.
    var profileCompleted: Bool {
        didSet { defaults.set(profileCompleted, forKey: Self.profileDoneKey) }
    }

    /// Payouts the user has logged as received, by settlement id, in
    /// whole dollars — the "recovered with Owed" ledger.
    private(set) var received: [String: Int] {
        didSet { defaults.set(received, forKey: Self.receivedKey) }
    }

    /// Settlement ids whose deadline is already in the user's calendar,
    /// so reopening the sheet can't create duplicate events.
    private(set) var calendared: Set<String> {
        didSet { defaults.set(Array(calendared), forKey: Self.calendaredKey) }
    }

    /// EventKit identifiers for calendared claims. Used to update the
    /// event in place when EventKit can resolve it; under write-only
    /// access the lookup fails and reconciliation falls back to the
    /// user-facing re-add flow (see CalendarHelper).
    private(set) var calendarEventIDs: [String: String] {
        didSet { defaults.set(calendarEventIDs, forKey: Self.calendarEventIDsKey) }
    }

    /// Local copy of every settlement the user tracks. The feed updates
    /// these but can't delete them — a settlement dropping out of the
    /// published feed must not vanish the user's claim, its status, or
    /// their logged payout.
    private(set) var trackedSnapshots: [String: Settlement] {
        didSet {
            if let data = try? JSONEncoder().encode(Array(trackedSnapshots.values)) {
                defaults.set(data, forKey: Self.snapshotsKey)
            }
        }
    }

    /// User-visible record of deadline changes on tracked claims, shown
    /// until dismissed. Courts extend deadlines; silently updating the
    /// date isn't enough when the user may have planned around the old
    /// one.
    private(set) var deadlineNotices: [DeadlineNotice] {
        didSet {
            if let data = try? JSONEncoder().encode(deadlineNotices) {
                defaults.set(data, forKey: Self.deadlineNoticesKey)
            }
        }
    }

    struct DeadlineNotice: Identifiable, Codable, Equatable {
        var id: String { settlementID }
        let settlementID: String
        let name: String
        let oldDeadline: Date
        let newDeadline: Date
    }

    /// Mirrored from StoreManager on launch and after purchase/restore.
    /// Turning true backfills deadline alerts for claims tracked before
    /// the purchase — the buyer's existing claims are exactly the ones
    /// they paid to be reminded about.
    var lifetime = false {
        didSet {
            guard lifetime, !oldValue else { return }
            let toSchedule = trackedSettlements
            Task {
                for s in toSchedule { await DeadlineAlerts.schedule(for: s) }
            }
        }
    }

    /// The published feed: last-good download when there is one, else the
    /// reviewed snapshot bundled with this build (FeedStore). Updated in
    /// place by `refreshFeed()`.
    private(set) var settlements: [Settlement]

    /// When the feed currently shown was generated by the publisher —
    /// surfaced in the UI as a freshness/trust signal.
    private(set) var feedGeneratedAt: Date?

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        tracked = Set(defaults.stringArray(forKey: Self.trackedKey) ?? [])
        profile = Set((defaults.stringArray(forKey: Self.profileKey) ?? []).compactMap(MatchKey.init))
        profileCompleted = defaults.bool(forKey: Self.profileDoneKey)
        received = (defaults.dictionary(forKey: Self.receivedKey) as? [String: Int]) ?? [:]
        calendared = Set(defaults.stringArray(forKey: Self.calendaredKey) ?? [])
        calendarEventIDs = (defaults.dictionary(forKey: Self.calendarEventIDsKey) as? [String: String]) ?? [:]

        if let data = defaults.data(forKey: Self.snapshotsKey),
           let saved = try? JSONDecoder().decode([Settlement].self, from: data) {
            trackedSnapshots = Dictionary(saved.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
        } else {
            trackedSnapshots = [:]
        }
        if let data = defaults.data(forKey: Self.deadlineNoticesKey),
           let saved = try? JSONDecoder().decode([DeadlineNotice].self, from: data) {
            deadlineNotices = saved
        } else {
            deadlineNotices = []
        }

        // Fast launch path: seed from the bundled snapshot only. It's
        // small and fixed-size, so it never blocks first frame; the
        // larger last-good disk cache is adopted asynchronously in
        // loadCachedFeed().
        let bundled = SettlementFeed.bundled()
        settlements = bundled?.settlements ?? []
        feedGeneratedAt = bundled?.generatedAt
        backfillTrackedSnapshots()
    }

    /// Users who tracked claims before snapshots existed: backfill from
    /// the current feed so their claims are protected from the first
    /// refresh onward.
    private func backfillTrackedSnapshots() {
        for s in settlements where tracked.contains(s.id) && trackedSnapshots[s.id] == nil {
            trackedSnapshots[s.id] = s
        }
    }

    /// Adopt the last-good disk cache if it's present and not older than
    /// what's shown. The disk read runs off the main actor so a large
    /// cached feed can't stall launch; the small decode lands back here.
    /// Call once at launch, before `refreshFeed()`.
    func loadCachedFeed() async {
        let data = await Task.detached(priority: .utility) { FeedStore.cachedData() }.value
        guard let data else { return }
        guard let cached = try? SettlementFeed.decode(data) else {
            FeedStore.discardCache()   // unreadable (e.g. schema bump) — drop it
            return
        }
        if let floor = feedGeneratedAt, cached.generatedAt < floor { return }
        settlements = cached.settlements
        feedGeneratedAt = cached.generatedAt
        backfillTrackedSnapshots()
    }

    // MARK: Feed refresh + reconciliation (Step 3)

    /// True while a refresh is in flight; also the overlap guard so
    /// rapid background/foreground cycles can't interleave reconciles.
    private var refreshing = false

    /// Fetches the latest feed and reconciles it against local state.
    /// Correctness order matters: tracked snapshots and deadline alerts
    /// update before the visible list, so the UI can't show a new
    /// deadline while notifications still fire for the old one.
    func refreshFeed() async {
        guard !refreshing else { return }
        refreshing = true
        defer { refreshing = false }
        guard let feed = await FeedStore.refresh(notOlderThan: feedGeneratedAt) else { return }
        reconcile(with: feed)
    }

    /// Internal (not private) so tests can drive reconciliation with
    /// constructed feeds instead of the network.
    func reconcile(with feed: SettlementFeed) {
        // Captured before the list updates so "new to this device" is
        // computed against what the user could actually have seen.
        let knownIDs = Set(settlements.map(\.id))

        for fresh in feed.settlements {
            guard tracked.contains(fresh.id) else { continue }
            let previous = trackedSnapshots[fresh.id]
            trackedSnapshots[fresh.id] = fresh

            // Deadline moved: stale T-7/T-1 alerts are the single most
            // user-visible correctness issue with live data. Reschedule,
            // and tell the user — they may have planned around the old
            // date.
            if let previous, previous.deadline != fresh.deadline {
                deadlineNotices.removeAll { $0.settlementID == fresh.id }
                deadlineNotices.append(DeadlineNotice(
                    settlementID: fresh.id,
                    name: fresh.name,
                    oldDeadline: previous.deadline,
                    newDeadline: fresh.deadline
                ))
                if lifetime {
                    DeadlineAlerts.cancel(for: fresh.id)
                    Task { await DeadlineAlerts.schedule(for: fresh) }
                }
                // Best-effort calendar update. Under write-only access
                // EventKit can't resolve our identifier — clear the flag
                // so the notice's one-tap re-add is available. If full
                // access (or a future OS) lets the update through, keep
                // calendared and the stored identifier. Legacy installs
                // that only have the boolean flag clear synchronously.
                if let eventID = calendarEventIDs[fresh.id] {
                    let settlement = fresh
                    Task {
                        let result = await CalendarHelper.updateDeadline(
                            for: settlement, eventIdentifier: eventID
                        )
                        if result != .updated {
                            calendared.remove(settlement.id)
                            calendarEventIDs[settlement.id] = nil
                        }
                    }
                } else if calendared.contains(fresh.id) {
                    calendared.remove(fresh.id)
                }
            }
        }

        settlements = feed.settlements
        feedGeneratedAt = feed.generatedAt
        SpotlightIndexer.index(settlements)

        // "We'll ping you the day a new settlement opens" — the Alerts
        // tab already promises this, so it must be true. Local-only for
        // now (fires when a refresh discovers the settlement); server
        // push (PIPELINE.md §5) later makes it same-day regardless of
        // app opens. Only for likely matches: a lifetime user's alert
        // channel is high-trust, and blasting every settlement burns it.
        if lifetime {
            let newMatches = feed.settlements.filter {
                !knownIDs.contains($0.id) && !$0.closed && isMatch($0)
            }
            Task {
                for s in newMatches { await DeadlineAlerts.notifyNewSettlement(s) }
            }
        }
    }

    func dismissDeadlineNotice(_ notice: DeadlineNotice) {
        deadlineNotices.removeAll { $0.id == notice.id }
    }

    func isTracked(_ s: Settlement) -> Bool { tracked.contains(s.id) }

    // MARK: Matching

    func isMatch(_ s: Settlement) -> Bool {
        s.matchKeys.contains { profile.contains($0) }
    }

    /// Settlements still open to file. The browse surfaces (Find feed,
    /// filters) and the match aggregate show only these — a closed
    /// settlement is not something the user can act on, so it never
    /// appears as browsable inventory or counts toward "likely matches."
    /// Closed settlements the user already tracks stay visible in My
    /// Claims via `trackedSettlements`, where they read as AWAITING
    /// PAYOUT; that path is intentionally separate.
    var browsableSettlements: [Settlement] {
        settlements.filter { !$0.closed }
    }

    var matchedSettlements: [Settlement] {
        browsableSettlements.filter(isMatch).sorted { $0.deadline < $1.deadline }
    }

    /// "You likely qualify for N settlements worth $lo–$hi."
    var matchedRange: String {
        let lo = matchedSettlements.reduce(0) { $0 + $1.payoutLo }
        let hi = matchedSettlements.reduce(0) { $0 + $1.payoutHi }
        return lo == hi ? lo.usd : "\(lo.usd)–\(hi.usd)"
    }

    // MARK: Claim lifecycle

    enum ClaimStatus: Equatable {
        case actionNeeded      // window closing soon — file now
        case pending           // filed, claims still open
        case awaitingPayout    // claims closed, distribution pending
        case paid(Int)         // user logged a received payout
    }

    func status(for s: Settlement) -> ClaimStatus {
        if let amount = received[s.id] { return .paid(amount) }
        if s.closed { return .awaitingPayout }
        if s.closingSoon { return .actionNeeded }
        return .pending
    }

    func recordPayment(_ s: Settlement, amount: Int) {
        received[s.id] = amount
    }

    func markCalendared(_ s: Settlement, eventIdentifier: String) {
        calendared.insert(s.id)
        calendarEventIDs[s.id] = eventIdentifier
    }

    /// One-tap re-add from a deadline-change notice when in-place update
    /// wasn't possible (write-only calendar access).
    func readdCalendar(for notice: DeadlineNotice) async -> Bool {
        guard let s = trackedSnapshots[notice.settlementID]
                ?? settlements.first(where: { $0.id == notice.settlementID })
        else { return false }
        guard let eventID = await CalendarHelper.addDeadline(for: s) else { return false }
        markCalendared(s, eventIdentifier: eventID)
        return true
    }

    /// Lifetime total the user has logged as recovered — the number that
    /// earns the App Store review prompt and the screenshot.
    var totalRecovered: Int {
        received.values.reduce(0, +)
    }

    func track(_ s: Settlement) {
        tracked.insert(s.id)
        trackedSnapshots[s.id] = s
        if lifetime {
            Task { await DeadlineAlerts.schedule(for: s) }
        }
    }

    /// Dropping a claim discards its logged payout too — the recovered
    /// ledger only counts claims the user is still tracking, so the
    /// Claims tab can't show a total with nothing under it.
    func untrack(_ s: Settlement) {
        tracked.remove(s.id)
        trackedSnapshots[s.id] = nil
        received[s.id] = nil
        calendared.remove(s.id)
        calendarEventIDs[s.id] = nil
        deadlineNotices.removeAll { $0.settlementID == s.id }
        DeadlineAlerts.cancel(for: s.id)
    }

    /// Tracked claims come from the local snapshots, not the feed — a
    /// settlement removed from the feed stays visible here (with its
    /// status and logged payout) until the user untracks it. Falls back
    /// to the feed only for ids tracked before snapshots existed.
    var trackedSettlements: [Settlement] {
        tracked
            .compactMap { id in trackedSnapshots[id] ?? settlements.first { $0.id == id } }
            .sorted { $0.deadline < $1.deadline }
    }

    /// Hero number as an honest range — anchoring on best-case totals
    /// over-promises and earns 1-star reviews when checks arrive.
    var potentialRange: String {
        let lo = trackedSettlements.reduce(0) { $0 + $1.payoutLo }
        let hi = trackedSettlements.reduce(0) { $0 + $1.payoutHi }
        return lo == hi ? lo.usd : "\(lo.usd)–\(hi.usd)"
    }
}

// MARK: - Local deadline alerts (lifetime perk)

/// T-7 / T-1 reminders for tracked claims, scheduled locally so the perk
/// works before the push pipeline (PIPELINE.md §5) exists. Server push
/// replaces this for "new settlement" alerts; these local ones remain a
/// good offline backstop.
enum DeadlineAlerts {
    /// Requests permission only while undetermined. Callers reach this
    /// right after a purchase or a tracked claim, so the system prompt
    /// lands with context instead of appearing out of nowhere.
    static func ensureAuthorized() async -> Bool {
        let center = UNUserNotificationCenter.current()
        switch await center.notificationSettings().authorizationStatus {
        case .notDetermined:
            return (try? await center.requestAuthorization(options: [.alert, .sound, .badge])) ?? false
        case .authorized, .provisional, .ephemeral:
            return true
        default:
            return false
        }
    }

    static func schedule(for s: Settlement) async {
        guard await ensureAuthorized() else { return }
        let center = UNUserNotificationCenter.current()
        let cal = Calendar.current

        for daysBefore in [7, 1] where s.daysLeft > daysBefore {
            // Anchor to the deadline date at 9am local — a relative
            // interval computed at track time drifts as the feed ages.
            guard let fireDay = cal.date(byAdding: .day, value: -daysBefore, to: s.deadline) else { continue }
            var comps = cal.dateComponents([.year, .month, .day], from: fireDay)
            comps.hour = 9

            let content = UNMutableNotificationContent()
            content.title = daysBefore == 1 ? "Last day tomorrow" : "One week left"
            content.body = "\(s.name) closes in \(daysBefore) day\(daysBefore == 1 ? "" : "s"). "
                + "Your claim isn't filed until the administrator confirms it."
            content.sound = .default

            let request = UNNotificationRequest(
                identifier: "owed.deadline.\(s.id).t\(daysBefore)",
                content: content,
                trigger: UNCalendarNotificationTrigger(dateMatching: comps, repeats: false)
            )
            try? await center.add(request)
        }
    }

    static func cancel(for settlementID: String) {
        UNUserNotificationCenter.current().removePendingNotificationRequests(
            withIdentifiers: [7, 1].map { "owed.deadline.\(settlementID).t\($0)" }
        )
    }

    /// A feed refresh discovered a settlement this user likely matches.
    /// Once-per-settlement is guaranteed by the caller (newness is
    /// computed against the persisted last-good feed); the stable
    /// identifier additionally collapses any same-session repeats.
    static func notifyNewSettlement(_ s: Settlement) async {
        guard await ensureAuthorized() else { return }

        let content = UNMutableNotificationContent()
        content.title = "New settlement you may qualify for"
        content.body = "\(s.name) — \(s.payoutRange) \(s.payoutTerms). "
            + "Claims close in \(s.daysLeft) day\(s.daysLeft == 1 ? "" : "s")."
        content.sound = .default

        try? await UNUserNotificationCenter.current().add(UNNotificationRequest(
            identifier: "owed.new.\(s.id)",
            content: content,
            trigger: nil
        ))
    }
}
